version: '3'

services:
  prometheus:
    image: prom/prometheus:latest #v2.49.1
    container_name: concurrency-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest #10.3.1
    container_name: concurrency-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src/main/resources/datasources:/etc/grafana/provisioning/datasources
      - ./src/main/resources/dashboards:/etc/grafana/provisioning/dashboards

  redis:
    image: redis:latest #7.2.4
    container_name: concurrency-redis
    restart: always
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    env_file:
      - .env
