---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrency-java
  labels:
    app: concurrency-java
spec:
  selector:
    matchLabels:
      app: concurrency-java
  replicas: 2
  template:
    metadata:
      labels:
        app: concurrency-java
    spec:
      containers:
        - name: concurrency-java
          image: 533267160846.dkr.ecr.us-east-2.amazonaws.com/metrics-concurrency:latest
          lifecycle:
            preStop: # avoid requests being routed to a pod that has already begun shutting down.
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: concurrency-config
          env:
            - name: JAVA_OPTS
              value: "--enable-preview"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: concurrency-java-svc
  labels:
    app: concurrency-java
spec:
  type: LoadBalancer
  selector:
    app: concurrency-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
