{
 "title": "Concurrency PoC 1.1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Factorial Timer Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "factorial_timer_seconds_max", "legendFormat": "__auto" },
    {
     "expr": "factorial_timer_threads_seconds_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "factorial_timer_virtual_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Factorial Timer Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "factorial_timer_seconds_max", "legendFormat": "__auto" },
    {
     "expr": "factorial_timer_threads_seconds_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "factorial_timer_virtual_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Square Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "square_hit_counter_total", "legendFormat": "__auto" },
    {
     "expr": "square_hit_counter_threads_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "square_hit_counter_virtual_total",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Square Timer Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "square_timer_seconds_max", "legendFormat": "__auto" },
    {
     "expr": "square_timer_threads_seconds_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "square_timer_virtual_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Square Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "square_key_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Factorial Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "factorial_key_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}