---
apiVersion: v1
kind: Service
metadata:
  name: concurrency-java-svc
  labels:
    app: concurrency-java
spec:
  type: LoadBalancer
  selector:
    app: concurrency-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: concurrency-redis-svc
  labels:
    app: concurrency-redis
spec:
  type: LoadBalancer
  selector:
    app: concurrency-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
